### PR TITLE
Use upstream apache module

### PR DESCRIPTION
**Pull request by Phil-Friderici**
Get back to upstream version (1.10.0) of the apache module again.

### CODE REVIEW

**Comment by Phil-Friderici** [comment]
This should do the trick, but please give it a test to verify the resulting vhost configuration is working as expected.

**Comment by ghoneycutt** [comment]
Just noticed that this should also remove `templates/yumrepo.conf.erb`

**Comment by jeffmccune** [comment]
@ghoneycutt @Phil-Friderici Please see my review above, do we expect name based virtual hosts to work when configuring a `yum::server`?  If so, changes are required, if not then validation has succeeded.

**Comment by ghoneycutt** [comment]
servername and aliases should work. The host would also have a real IP.

**Comment by jeffmccune** [comment]
> servername and aliases should work. The host would also have a real IP.

Got it, however those aliases only work through the configured vhost IP address (`$::ipaddress`).  That is to say, when an HTTP client tries to access `infra-test01` (Configured with `ServerAlias infra-test01`) using an IP other than the one listed in `<VirtualHost 10.0.2.15:80>`, e.g. over 127.0.0.1, or some other interface, then a 404 will result.

**Pull request merged**
